/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0
 * Generated at: 2024-11-11 15:19:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.index;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/WebMP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebMyPham/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1731334434720L));
    _jspx_dependants.put("jar:file:/E:/WebMP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebMyPham/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn-1_1.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	background-color: #f8f8f8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_content_sub_login {\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	margin: 50px auto;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	border: 1px solid #e5e5e5;\r\n");
      out.write("	box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group .parent_code_register {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group input[type=\"text\"], .form-group input[type=\"password\"],\r\n");
      out.write("	.form-group select {\r\n");
      out.write("	width: 200%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group input[type=\"checkbox\"] {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group i {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 10px;\r\n");
      out.write("	top: 12px;\r\n");
      out.write("	color: #aaa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row .form-control {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-inline {\r\n");
      out.write("	margin-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".radio-inline input {\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".group-birthday select {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checkbox-inline {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checkbox-inline input {\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_site_1 {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #326e51;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_site_1:hover {\r\n");
      out.write("	background-color: #285a42;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".block_login_fb {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".block_login_fb img {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.txt_color_1 {\r\n");
      out.write("	color: #326e51;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.txt_color_1:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".space_bottom_10 {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"main_content_sub_login\">\r\n");
      out.write("		<form id=\"form-head-register\" action=\"\" method=\"post\"\r\n");
      out.write("			novalidate=\"novalidate\">\r\n");
      out.write("			<input name=\"form_key\" type=\"hidden\" value=\"9lB2QzSyHmzVefcW\">\r\n");
      out.write("			<div class=\"block_more_login\">\r\n");
      out.write("				<div class=\"space_bottom_10\">Đăng ký tài khoản</div>\r\n");
      out.write("				<div class=\"showRegisterMessage text-danger hidden\"></div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"relative\">\r\n");
      out.write("						<input type=\"text\" class=\"form-control email\" name=\"email\"\r\n");
      out.write("							id=\"reg-email\" placeholder=\"Nhập email hoặc số điện thoại\">\r\n");
      out.write("						<i aria-hidden=\"true\" class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"form-group \">\r\n");
      out.write("					<div class=\"relative parent_code_register\">\r\n");
      out.write("						<input autocomplete=\"off\" placeholder=\"Nhập mã xác thực 6 số\"\r\n");
      out.write("							type=\"text\" name=\"code\" title=\"Code\"\r\n");
      out.write("							class=\"codeRegister input-text\">\r\n");
      out.write("						<button type=\"button\" data-resend-time=\"\"\r\n");
      out.write("							class=\"show-resend hidden\" >\r\n");
      out.write("							<span class=\"minute\">--</span>:<span class=\"second\">--</span>\r\n");
      out.write("						</button>\r\n");
      out.write("						<button type=\"button\" id=\"verifyUserName\"\r\n");
      out.write("							data-error=\".showRegisterMessage\" >lấy\r\n");
      out.write("							mã</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"relative\">\r\n");
      out.write("						<input id=\"reg-password\" autocomplete=\"off\" name=\"password\"\r\n");
      out.write("							type=\"password\" placeholder=\"Nhập mật khẩu từ 6 - 32 ký tự\"\r\n");
      out.write("							class=\"form-control\"> <i aria-hidden=\"true\"\r\n");
      out.write("							class=\"fa fa-lock\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"relative\">\r\n");
      out.write("						<input id=\"reg-fullname\" name=\"fullname\" type=\"text\"\r\n");
      out.write("							placeholder=\"Họ tên\" class=\"form-control\"\r\n");
      out.write("							data-validate=\"{required:true, 'validate-custom-fullname': true}\">\r\n");
      out.write("						<i aria-hidden=\"true\" class=\"fa fa-user\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<div class=\"col-lg-4\">\r\n");
      out.write("						<label class=\"radio-inline\"><input name=\"gender\" value=\"0\"\r\n");
      out.write("							type=\"radio\">Không xác định </label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2\">\r\n");
      out.write("						<label class=\"radio-inline\"><input name=\"gender\" value=\"1\"\r\n");
      out.write("							type=\"radio\"> Nam </label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2\">\r\n");
      out.write("						<label class=\"radio-inline\"><input name=\"gender\" value=\"2\"\r\n");
      out.write("							type=\"radio\" checked=\"checked\"> Nữ </label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row group-birthday\">\r\n");
      out.write("					<div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-4\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<select class=\"form-control\" name=\"popup-date\" id=\"reg-day\">\r\n");
      out.write("								<option value=\"\">Ngày</option>\r\n");
      out.write("								<option value=\"1\">1</option>\r\n");
      out.write("								<option value=\"2\">2</option>\r\n");
      out.write("								<option value=\"3\">3</option>\r\n");
      out.write("								<option value=\"4\">4</option>\r\n");
      out.write("								<option value=\"5\">5</option>\r\n");
      out.write("								<option value=\"6\">6</option>\r\n");
      out.write("								<option value=\"7\">7</option>\r\n");
      out.write("								<option value=\"8\">8</option>\r\n");
      out.write("								<option value=\"9\">9</option>\r\n");
      out.write("								<option value=\"10\">10</option>\r\n");
      out.write("								<option value=\"11\">11</option>\r\n");
      out.write("								<option value=\"12\">12</option>\r\n");
      out.write("								<option value=\"13\">13</option>\r\n");
      out.write("								<option value=\"14\">14</option>\r\n");
      out.write("								<option value=\"15\">15</option>\r\n");
      out.write("								<option value=\"16\">16</option>\r\n");
      out.write("								<option value=\"17\">17</option>\r\n");
      out.write("								<option value=\"18\">18</option>\r\n");
      out.write("								<option value=\"19\">19</option>\r\n");
      out.write("								<option value=\"20\">20</option>\r\n");
      out.write("								<option value=\"21\">21</option>\r\n");
      out.write("								<option value=\"22\">22</option>\r\n");
      out.write("								<option value=\"23\">23</option>\r\n");
      out.write("								<option value=\"24\">24</option>\r\n");
      out.write("								<option value=\"25\">25</option>\r\n");
      out.write("								<option value=\"26\">26</option>\r\n");
      out.write("								<option value=\"27\">27</option>\r\n");
      out.write("								<option value=\"28\">28</option>\r\n");
      out.write("								<option value=\"29\">29</option>\r\n");
      out.write("								<option value=\"30\">30</option>\r\n");
      out.write("								<option value=\"31\">31</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-4\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<select class=\"form-control\" name=\"popup-month\" id=\"reg-month\">\r\n");
      out.write("								<option value=\"\">Tháng</option>\r\n");
      out.write("								<option value=\"1\">1</option>\r\n");
      out.write("								<option value=\"2\">2</option>\r\n");
      out.write("								<option value=\"3\">3</option>\r\n");
      out.write("								<option value=\"4\">4</option>\r\n");
      out.write("								<option value=\"5\">5</option>\r\n");
      out.write("								<option value=\"6\">6</option>\r\n");
      out.write("								<option value=\"7\">7</option>\r\n");
      out.write("								<option value=\"8\">8</option>\r\n");
      out.write("								<option value=\"9\">9</option>\r\n");
      out.write("								<option value=\"10\">10</option>\r\n");
      out.write("								<option value=\"11\">11</option>\r\n");
      out.write("								<option value=\"12\">12</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-4\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<select class=\"form-control\" name=\"popup-year\" id=\"reg-year\">\r\n");
      out.write("								<option value=\"\">Năm</option>\r\n");
      out.write("								<option value=\"2008\">2008</option>\r\n");
      out.write("								<option value=\"2007\">2007</option>\r\n");
      out.write("								<option value=\"2006\">2006</option>\r\n");
      out.write("								<option value=\"2005\">2005</option>\r\n");
      out.write("								<option value=\"2004\">2004</option>\r\n");
      out.write("								<option value=\"2003\">2003</option>\r\n");
      out.write("								<option value=\"2002\">2002</option>\r\n");
      out.write("								<option value=\"2001\">2001</option>\r\n");
      out.write("								<option value=\"2000\">2000</option>\r\n");
      out.write("								<option value=\"1999\">1999</option>\r\n");
      out.write("								<option value=\"1998\">1998</option>\r\n");
      out.write("								<option value=\"1997\">1997</option>\r\n");
      out.write("								<option value=\"1996\">1996</option>\r\n");
      out.write("								<option value=\"1995\">1995</option>\r\n");
      out.write("								<option value=\"1994\">1994</option>\r\n");
      out.write("								<option value=\"1993\">1993</option>\r\n");
      out.write("								<option value=\"1992\">1992</option>\r\n");
      out.write("								<option value=\"1991\">1991</option>\r\n");
      out.write("								<option value=\"1990\">1990</option>\r\n");
      out.write("								<option value=\"1989\">1989</option>\r\n");
      out.write("								<option value=\"1988\">1988</option>\r\n");
      out.write("								<option value=\"1987\">1987</option>\r\n");
      out.write("								<option value=\"1986\">1986</option>\r\n");
      out.write("								<option value=\"1985\">1985</option>\r\n");
      out.write("								<option value=\"1984\">1984</option>\r\n");
      out.write("								<option value=\"1983\">1983</option>\r\n");
      out.write("								<option value=\"1982\">1982</option>\r\n");
      out.write("								<option value=\"1981\">1981</option>\r\n");
      out.write("								<option value=\"1980\">1980</option>\r\n");
      out.write("								<option value=\"1979\">1979</option>\r\n");
      out.write("								<option value=\"1978\">1978</option>\r\n");
      out.write("								<option value=\"1977\">1977</option>\r\n");
      out.write("								<option value=\"1976\">1976</option>\r\n");
      out.write("								<option value=\"1975\">1975</option>\r\n");
      out.write("								<option value=\"1974\">1974</option>\r\n");
      out.write("								<option value=\"1973\">1973</option>\r\n");
      out.write("								<option value=\"1972\">1972</option>\r\n");
      out.write("								<option value=\"1971\">1971</option>\r\n");
      out.write("								<option value=\"1970\">1970</option>\r\n");
      out.write("								<option value=\"1969\">1969</option>\r\n");
      out.write("								<option value=\"1968\">1968</option>\r\n");
      out.write("								<option value=\"1967\">1967</option>\r\n");
      out.write("								<option value=\"1966\">1966</option>\r\n");
      out.write("								<option value=\"1965\">1965</option>\r\n");
      out.write("								<option value=\"1964\">1964</option>\r\n");
      out.write("								<option value=\"1963\">1963</option>\r\n");
      out.write("								<option value=\"1962\">1962</option>\r\n");
      out.write("								<option value=\"1961\">1961</option>\r\n");
      out.write("								<option value=\"1960\">1960</option>\r\n");
      out.write("								<option value=\"1959\">1959</option>\r\n");
      out.write("								<option value=\"1958\">1958</option>\r\n");
      out.write("								<option value=\"1957\">1957</option>\r\n");
      out.write("								<option value=\"1956\">1956</option>\r\n");
      out.write("								<option value=\"1955\">1955</option>\r\n");
      out.write("								<option value=\"1954\">1954</option>\r\n");
      out.write("								<option value=\"1953\">1953</option>\r\n");
      out.write("								<option value=\"1952\">1952</option>\r\n");
      out.write("								<option value=\"1951\">1951</option>\r\n");
      out.write("								<option value=\"1950\">1950</option>\r\n");
      out.write("								<option value=\"1949\">1949</option>\r\n");
      out.write("								<option value=\"1948\">1948</option>\r\n");
      out.write("								<option value=\"1947\">1947</option>\r\n");
      out.write("								<option value=\"1946\">1946</option>\r\n");
      out.write("								<option value=\"1945\">1945</option>\r\n");
      out.write("								<option value=\"1944\">1944</option>\r\n");
      out.write("								<option value=\"1943\">1943</option>\r\n");
      out.write("								<option value=\"1942\">1942</option>\r\n");
      out.write("								<option value=\"1941\">1941</option>\r\n");
      out.write("								<option value=\"1940\">1940</option>\r\n");
      out.write("								<option value=\"1939\">1939</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label class=\"checkbox-inline\"> <input\r\n");
      out.write("						name=\"accept_policy_privacy\" value=\"1\" checked=\"checked\"\r\n");
      out.write("						type=\"checkbox\" id=\"reg-policy\"> Tôi đã đọc và đồng ý với\r\n");
      out.write("						<a href=\"https://hotro.hasaki.vn/quy-dinh-giao-dich-chung.html\"\r\n");
      out.write("						style=\"color: #326e51\">Điều kiện giao dịch chung</a> và <a\r\n");
      out.write("						href=\"https://hotro.hasaki.vn/chinh-sach-bao-mat.html\"\r\n");
      out.write("						style=\"color: #326e51\">Chính sách bảo mật thông tin</a> của Hasaki\r\n");
      out.write("					</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label class=\"checkbox-inline\"> <input name=\"is_subscribed\"\r\n");
      out.write("						value=\"1\" checked=\"checked\" type=\"checkbox\"> Nhận thông\r\n");
      out.write("						tin khuyến mãi qua e-mail\r\n");
      out.write("					</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clearfix\"></div>\r\n");
      out.write("				<button class=\"btn btn_site_1\" id=\"btnRegister\">Đăng ký</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<div class=\"block_login_fb\">\r\n");
      out.write("			Bạn đã có tài khoản? <a href=\"#popup-login\"\r\n");
      out.write("				class=\"txt_color_1 text-uppercase popup-login popup-register-dismiss\">Đăng\r\n");
      out.write("				nhập</a>\r\n");
      out.write("			<div class=\"space_bottom_10\">Hoặc đăng nhập với:</div>\r\n");
      out.write("			<a class=\"login-facebook\" href=\"javascript:void(0);\"\r\n");
      out.write("				data-href=\"https://hasaki.vn/login-facebook\"> <img\r\n");
      out.write("				src=\"https://hasaki.vn/images/graphics/img_login_fb_2.jpg\" alt=\"\"\r\n");
      out.write("				class=\"loading\" data-was-processed=\"true\">\r\n");
      out.write("			</a> &nbsp; <a class=\"login-google\" href=\"javascript:void(0);\"\r\n");
      out.write("				data-href=\"https://hasaki.vn/login-google\"> <img\r\n");
      out.write("				src=\"https://hasaki.vn/images/graphics/img_login_gg_2.jpg\" alt=\"\"\r\n");
      out.write("				class=\"loading\" data-was-processed=\"true\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById(\"verifyUserName\").addEventListener(\"click\", function() {\r\n");
      out.write("        var email = document.getElementById(\"reg-email\").value;\r\n");
      out.write("        if (email === \"\") {\r\n");
      out.write("            alert(\"Vui lòng nhập email.\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Gửi yêu cầu AJAX đến servlet\r\n");
      out.write("        var xhr = new XMLHttpRequest();\r\n");
      out.write("        xhr.open(\"POST\", \"../SendEmail\", true);\r\n");
      out.write("        xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write("        xhr.onreadystatechange = function() {\r\n");
      out.write("            if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                if (xhr.responseText === \"success\") {\r\n");
      out.write("                    alert(\"Mã xác nhận đã được gửi đến email của bạn.\");\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"Gửi mã thất bại. Vui lòng thử lại.\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("        xhr.send(\"email=\" + encodeURIComponent(email));\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
