/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0
 * Generated at: 2024-11-10 08:12:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.io.Console;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.io.Console");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Web Mỹ Phẩm</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"web-service\">\r\n");
      out.write("		<header class=\"header\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"top-banner\">\r\n");
      out.write("				<p>22.10 Ưu Đãi Đỉnh Nóc & Giờ Vàng Deal Sốc - Duy Nhất Từ 11h\r\n");
      out.write("					Ngày 22.10 (Áp Dụng Online)</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"header-main\">\r\n");
      out.write("				<div class=\"logo-left\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"logo\">\r\n");
      out.write("						<img src=\"img/logo.png\" alt=\"NThanh.vn\">\r\n");
      out.write("						<div class=\"logo-text\">\r\n");
      out.write("							<h3>TTT.vn</h3>\r\n");
      out.write("							<span>Chất lượng thật - Giá trị thật</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"search-bar\">\r\n");
      out.write("						<input type=\"text\" placeholder=\"Tìm kiếm sản phẩm...\"\r\n");
      out.write("							id=\"search-input\">\r\n");
      out.write("						<div class=\"search-notification\">\r\n");
      out.write("							<div class=\"notification-container\">\r\n");
      out.write("								<ul class=\"notifications\">\r\n");
      out.write("									<li>24-26.10 Halloween Cực Chất - Săn Deal Độc Nhất\r\n");
      out.write("										(Online Từ 12H)</li>\r\n");
      out.write("									<li>Khai trương CN224 Q. Bình Tân, TP. HCM | Deal 2K (Chỉ\r\n");
      out.write("										27/10)</li>\r\n");
      out.write("									<li>Khai trương CN223 TP. Hội An, Quảng Nam | Deal 2K (Chỉ\r\n");
      out.write("										27/10)</li>\r\n");
      out.write("									<li>Mua Gì Cũng Rẻ - Dưới 99K</li>\r\n");
      out.write("									<li>Giảm 200K/Gói Triệt Lông Diode Laser Cho HSSV Nữ</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Phần danh mục và thương hiệu -->\r\n");
      out.write("							<div class=\"category-brand-container\">\r\n");
      out.write("								<div class=\"category-title\">\r\n");
      out.write("									<span>Nước Hoa</span>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"categories\">\r\n");
      out.write("									<div class=\"category-item\">Trang Điểm Mặt</div>\r\n");
      out.write("									<div class=\"category-item\">Trang Điểm Môi</div>\r\n");
      out.write("									<div class=\"category-item\">Mặt Nạ</div>\r\n");
      out.write("									<div class=\"category-item\">Sữa Tắm</div>\r\n");
      out.write("									<div class=\"category-item\">Bộ Trang Điểm</div>\r\n");
      out.write("									<div class=\"category-item\">Vấn Đề Về Da</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"brands\">\r\n");
      out.write("									<img\r\n");
      out.write("										src=\"https://media.hcdn.vn/brand/1593168007the-coc_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"L'Oreal\"> <img\r\n");
      out.write("										src=\"https://media.hcdn.vn//hsk/brandnaris-cosmetics-logo1716963318_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"Skin Aqua\"> <img\r\n");
      out.write("										src=\"https://media.hcdn.vn/hsk/brand/Sunplay-Skin-Aqua1662624548_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"Eucerin\"> <img\r\n");
      out.write("										src=\"https://media.hcdn.vn/hsk/brand/Sunplay-Skin-Aqua1662624548_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"Klairs\"> <img\r\n");
      out.write("										src=\"https://media.hcdn.vn//hsk/brandEucerin-logo1690282206_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"Garnier\"> <img\r\n");
      out.write("										src=\"https://media.hcdn.vn//hsk/brandSkin10041678681869_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"Skin1004\"> <img\r\n");
      out.write("										src=\"https://media.hcdn.vn/brand/1661766124cetaphil_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"Judydoll\"> <img\r\n");
      out.write("										src=\"https://media.hcdn.vn//hsk/brandHada-labo-logo1690282339_img_150x75_766519_fit_center.jpg\"\r\n");
      out.write("										alt=\"Dove\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"button\" id=\"find-product\">Tìm kiếm</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"float-right\">\r\n");
      out.write("					<div class=\"header-icons\">\r\n");
      out.write("						<img src=\"https://hasaki.vn/images/graphics/icon_header_2.svg\">\r\n");
      out.write("						<div class=\"login-hover\">\r\n");
      out.write("							<a href=\"src/index/login.jsp\" target=\"_blank\" class=\"login\">Đăng\r\n");
      out.write("								nhập/ <a href=\"index/signUp.jsp\" target=\"_blank\">Đăng ký </br>Tài\r\n");
      out.write("									khoản &darr;\r\n");
      out.write("							</a>\r\n");
      out.write("								<div class=\"login-box\">\r\n");
      out.write("									<h3>Đăng nhập với</h3>\r\n");
      out.write("									<div class=\"social-login\">\r\n");
      out.write("										<button class=\"facebook-login\">\r\n");
      out.write("											<img\r\n");
      out.write("												src=\"https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg\"\r\n");
      out.write("												alt=\"Facebook logo\"> Facebook\r\n");
      out.write("										</button>\r\n");
      out.write("										<button class=\"google-login\">\r\n");
      out.write("											<img\r\n");
      out.write("												src=\"https://upload.wikimedia.org/wikipedia/commons/4/4a/Logo_2013_Google.png\"\r\n");
      out.write("												alt=\"Google logo\"> Google +\r\n");
      out.write("										</button>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p>Hoặc đăng nhập với Nthanh.vn</p>\r\n");
      out.write("									<button class=\"hasaki-login\"\r\n");
      out.write("										onclick=\"window.location.href='login.jsp'\">Đăng nhập</button>\r\n");
      out.write("									<p>\r\n");
      out.write("										Bạn chưa có tài khoản? <a href=\"index/signUp.jsp\">ĐĂNG KÝ NGAY</a>\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"header-icon-sub\">\r\n");
      out.write("							<img\r\n");
      out.write("								src=\"https://hasaki.vn/images/graphics/icon_header_store.svg\">\r\n");
      out.write("							<a href=\"#\" id=\"htch\"> Hệ thống</br> cửa hàng\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"header-icon-sub\">\r\n");
      out.write("							<img src=\"https://hasaki.vn/images/graphics/icon_header_3.svg\">\r\n");
      out.write("							<a href=\"#\" id=\"htkh\"> Hỗ trợ </br>khách hàng\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"header-icon-sub\">\r\n");
      out.write("							<img src=\"https://hasaki.vn/images/graphics/icon_header_1.svg\">\r\n");
      out.write("\r\n");
      out.write("							<a href=\"cartProduct.html\" class=\"cart-icon\"> Giỏ hàng <span\r\n");
      out.write("								class=\"cart-count\">2</span></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header-list-product\">\r\n");
      out.write("				<nav class=\"navbar\">\r\n");
      out.write("					<ul class=\"nav-menu\">\r\n");
      out.write("						<div class=\"paddig-hover\">\r\n");
      out.write("							<li id=\"sub-menu-hover\"><a href=\"\">☰ DANH MỤC</a></li>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"sub-menu-web\">\r\n");
      out.write("							<div class=\"col-menu-cap1\">\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Sức Khỏe - Làm Đẹp</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Mỹ Phẩm High-End</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Chăm Sóc Da Mặt</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Trang Điểm</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Chăm Sóc Tóc Và Da Đầu</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Chăm Sóc Cơ Thể</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Chăm Sóc Cá Nhân</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Nước Hoa</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Thực Phẩm Chức Năng</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"sub-item-menu\">\r\n");
      out.write("									<a href=\"#\">Dịch Vụ Trải Nghiệm</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<li><a href=\"#\">HASAKI DEALS</a></li>\r\n");
      out.write("						<li><a href=\"#\">HOT DEALS</a></li>\r\n");
      out.write("						<li><a href=\"#\">THƯƠNG HIỆU</a></li>\r\n");
      out.write("						<li><a href=\"#\">HÀNG MỚI VỀ</a></li>\r\n");
      out.write("						<li><a href=\"#\">BÁN CHẠY</a></li>\r\n");
      out.write("						<li><a href=\"#\">CLINIC & SPA</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"nav-right\">\r\n");
      out.write("						<li><a href=\"#\">Tra cứu đơn hàng</a></li>\r\n");
      out.write("						<li><a href=\"#\">Tải ứng dụng</a></li>\r\n");
      out.write("						<li><a href=\"#\">Chọn khu vực của bạn</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("	<script src=\"js/updateUserMain.js\">\r\n");
      out.write("	</script>\r\n");
      out.write("	");

	String username = (String) session.getAttribute("username");
	
	
	if (username == null) {
		username = ""; // Hoặc một giá trị mặc định nếu chưa đăng nhập
	}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	const username = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("    loginUser();\r\n");
      out.write("    // Lấy danh sách tất cả các phần tử có class \"logout-account\"\r\n");
      out.write("    var logoutElements = document.getElementsByClassName(\"logout-account\");\r\n");
      out.write("\r\n");
      out.write("    // Thêm sự kiện onclick cho từng phần tử\r\n");
      out.write("    Array.from(logoutElements).forEach(element => {\r\n");
      out.write("        element.onclick = function () {\r\n");
      out.write("            logoutUser();\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    var htkh = document.getElementById('htkh');\r\n");
      out.write("    htkh.onclick = function () {\r\n");
      out.write("        window.location.href = 'htkh.html';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    var htch = document.getElementById('htch');\r\n");
      out.write("    htch.onclick = function () {\r\n");
      out.write("        window.location.href = 'htch.html'\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
